### ISSUE TITLE
Django 4 support

### ISSUE THREAD

**Issue by N1K1TAS95** [manikos/django-vimage#2]
### Django 4 support

Hi!
Is it possible to add support for Django 4?
The old ugettext_lazy has been replaced by gettext_lazy for internalization functions and as a result I cannot use django-vimage.

Thank you

**Comment by manikos** [comment]
Sure, I'll add support for Django 4. Thanks for using my package :)

**Comment by manikos** [comment]
@N1K1TAS95 Support for Django 4.0 (`pip install -U django-vimage`) has been added. Test it please :)

**Comment by N1K1TAS95** [comment]
@manikos works like a charm!
Tx
